name: Build and push Docker image to container registry

on:
  push:
    branches: [master]

jobs: 
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ui:${{ github.sha }}
            ghcr.io/${{ github.repository }}/ui:master
            ghcr.io/${{ github.repository }}/ui:latest